FROM php:8.3.17-apache

RUN apt-get update;
RUN apt-get install -y nano;
RUN apt-get install -y vim;
RUN apt-get install -y net-tools;
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql